name: CI/CD workflow

on: workflow_dispatch

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: sentiment-app-onnx

defaults:
  run:
    working-directory: lab11

jobs:
  integration:
    name: checks_and_tests
    runs-on: ubuntu-latest
    steps:
      - name: Show run info
        run: |
          echo "SHA: ${{ github.sha }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Show region
        run: echo "Deploying to ${{ env.AWS_REGION }}"

      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --group integration

      - name: Ruff check
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest tests/ -v
